# Stubs for pendulum.parsing (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .exceptions import ParserError
from .iso8601 import parse_iso8601
from typing import Any, Optional

with_extensions: Any
COMMON: Any
DEFAULT_OPTIONS: Any

def parse(text: Any, **options: Any): ...

class _Interval:
    start: Any = ...
    end: Any = ...
    duration: Any = ...
    def __init__(
        self,
        start: Optional[Any] = ...,
        end: Optional[Any] = ...,
        duration: Optional[Any] = ...,
    ) -> None: ...
