# Stubs for pendulum.parsing.iso8601 (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..constants import (
    HOURS_PER_DAY,
    MINUTES_PER_HOUR,
    MONTHS_OFFSETS,
    SECONDS_PER_MINUTE,
)
from ..duration import Duration
from ..helpers import days_in_year, is_leap, is_long_year, week_day
from ..tz.timezone import FixedTimezone
from .exceptions import ParserError
from typing import Any

ISO8601_DT: Any
ISO8601_DURATION: Any

def parse_iso8601(text: Any): ...
