# Stubs for pendulum.mixins.default (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..formatting import Formatter
from typing import Any, Optional

class FormattableMixing:
    def format(self, fmt: Any, locale: Optional[Any] = ...): ...
    def for_json(self): ...
    def __format__(self, format_spec: Any): ...
