# Stubs for pendulum.tz.zoneinfo (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .reader import Reader
from .timezone import Timezone

def read(name: str, extend: bool = ...) -> Timezone: ...
def read_file(path: str, extend: bool = ...) -> Timezone: ...
