# Stubs for pendulum.exceptions (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .parsing.exceptions import ParserError

class PendulumException(Exception): ...
