# Stubs for pendulum.helpers (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import pendulum
from ._extensions.helpers import days_in_year as days_in_year
from ._extensions.helpers import is_leap as is_leap
from ._extensions.helpers import is_long_year as is_long_year
from ._extensions.helpers import local_time as local_time
from ._extensions.helpers import precise_diff as precise_diff
from ._extensions.helpers import timestamp as timestamp
from ._extensions.helpers import week_day as week_day
from .constants import DAYS_PER_MONTHS as DAYS_PER_MONTHS
from .formatting.difference_formatter import DifferenceFormatter as DifferenceFormatter
from .locales.locale import Locale
from .period import Period
from datetime import date, datetime
from typing import Any, Iterator, Optional, TypeVar

with_extensions: Any
_DT = TypeVar("_DT", bound=datetime)
_D = TypeVar("_D", bound=date)
difference_formatter: Any

def add_duration(
    dt: _DT,
    years: int = ...,
    months: int = ...,
    weeks: int = ...,
    days: int = ...,
    hours: int = ...,
    minutes: int = ...,
    seconds: int = ...,
    microseconds: int = ...,
) -> _DT: ...
def format_diff(
    diff: Period, is_now: bool = ..., absolute: bool = ..., locale: Optional[str] = ...
) -> str: ...
def test(mock: pendulum.DateTime) -> Iterator[None]: ...
def set_test_now(test_now: Optional[pendulum.DateTime] = ...) -> None: ...
def get_test_now() -> Optional[pendulum.DateTime]: ...
def has_test_now() -> bool: ...
def locale(name: str) -> Locale: ...
def set_locale(name: str) -> None: ...
def get_locale() -> str: ...
def week_starts_at(wday: int) -> None: ...
def week_ends_at(wday: int) -> None: ...
