# Stubs for pendulum.parser (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import typing
from .parsing import _Interval
from .tz import UTC

def parse(text: str, **options: typing.Any) -> str: ...
