# Stubs for pendulum.tz.local_timezone (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .timezone import Timezone, TimezoneFile
from .zoneinfo.exceptions import InvalidTimezone
from typing import Iterator, Optional, Union

def get_local_timezone() -> Timezone: ...
def set_local_timezone(mock: Optional[Union[str, Timezone]] = ...) -> None: ...
def test_local_timezone(mock: Timezone) -> Iterator[None]: ...
