# Stubs for pendulum.tz.timezone (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .exceptions import AmbiguousTime, NonExistingTime
from .zoneinfo import read, read_file
from .zoneinfo.transition import Transition
from datetime import datetime, timedelta, tzinfo
from typing import Any, Optional, TypeVar, overload

POST_TRANSITION: str
PRE_TRANSITION: str
TRANSITION_ERROR: str
_datetime = datetime
_D = TypeVar("_D", bound=datetime)

class Timezone(tzinfo):
    def __init__(self, name: str, extended: bool = ...) -> None: ...
    @property
    def name(self) -> str: ...
    def convert(self, dt: _D, dst_rule: Optional[str] = ...) -> _D: ...
    def datetime(
        self,
        year: int,
        month: int,
        day: int,
        hour: int = ...,
        minute: int = ...,
        second: int = ...,
        microsecond: int = ...,
    ) -> _datetime: ...
    @overload
    def utcoffset(self, dt: None) -> None: ...
    @overload
    def utcoffset(self, dt: _datetime) -> timedelta: ...
    @overload
    def utcoffset(self, dt: Any): ...
    def dst(self, dt: Optional[_datetime]) -> Optional[timedelta]: ...
    def tzname(self, dt: Optional[_datetime]) -> Optional[str]: ...
    def fromutc(self, dt: _D) -> _D: ...
    def __getinitargs__(self) -> tuple: ...  # type: ignore

class FixedTimezone(Timezone):
    def __init__(self, offset: Any, name: Optional[Any] = ...) -> None: ...
    @property
    def offset(self) -> int: ...
    def utcoffset(self, dt: Optional[_datetime]) -> timedelta: ...  # type: ignore
    def dst(self, dt: Optional[_datetime]) -> timedelta: ...
    def fromutc(self, dt: _D) -> _D: ...
    def tzname(self, dt: Optional[_datetime]) -> Optional[str]: ...
    def __getinitargs__(self) -> tuple: ...  # type: ignore

class TimezoneFile(Timezone):
    def __init__(self, path: Any) -> None: ...

UTC: FixedTimezone
