# Stubs for pendulum.utils._compat (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

PY2: Any
PY36: Any
PYPY: Any
_HAS_FOLD = PY36
long = int
unicode = str
basestring = str

def decode(string: Any, encodings: Optional[Any] = ...): ...
def encode(string: Any, encodings: Optional[Any] = ...): ...
