# Stubs for pendulum._extensions.helpers (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import datetime
import typing
from ..constants import (
    DAYS_PER_L_YEAR,
    DAYS_PER_MONTHS,
    DAYS_PER_N_YEAR,
    DAY_OF_WEEK_TABLE,
    EPOCH_YEAR,
    MONTHS_OFFSETS,
    SECS_PER_100_YEARS,
    SECS_PER_400_YEARS,
    SECS_PER_4_YEARS,
    SECS_PER_DAY,
    SECS_PER_HOUR,
    SECS_PER_MIN,
    SECS_PER_YEAR,
    TM_DECEMBER,
    TM_JANUARY,
)

class PreciseDiff: ...

def is_leap(year: int) -> bool: ...
def is_long_year(year: int) -> bool: ...
def week_day(year: int, month: int, day: int) -> int: ...
def days_in_year(year: int) -> int: ...
def timestamp(dt: datetime.datetime) -> int: ...
def local_time(
    unix_time: int, utc_offset: int, microseconds: int
) -> typing.Tuple[int, int, int, int, int, int, int]: ...
def precise_diff(
    d1: typing.Union[datetime.datetime, datetime.date],
    d2: typing.Union[datetime.datetime, datetime.date],
) -> PreciseDiff: ...
