# Stubs for pendulum.formatting.difference_formatter (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import typing
from ..locales.locale import Locale
from ..period import Period

class DifferenceFormatter:
    def __init__(self, locale: str = ...) -> None: ...
    def format(
        self,
        diff: Period,
        is_now: bool = ...,
        absolute: bool = ...,
        locale: typing.Optional[str] = ...,
    ) -> str: ...
