# Stubs for pendulum.formatting.formatter (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import pendulum
import typing
from pendulum.locales.locale import Locale

class Formatter:
    def format(
        self,
        dt: pendulum.DateTime,
        fmt: str,
        locale: typing.Optional[typing.Union[str, Locale]] = ...,
    ) -> str: ...
    def parse(
        self,
        time: str,
        fmt: str,
        now: pendulum.DateTime,
        locale: typing.Optional[str] = ...,
    ) -> typing.Dict[str, typing.Any]: ...
